site_name: software notes
nav:
    - Overview: README.md
    - Genetic analysis:
      - AA.md
      - CRISPR.md
      - misc.md
      - NGS.md
      - pharmacogenomics.md*
      - prottrans.md*
      - scRNASeq.md*
    - SL: SL.md
    - AI: AI.md
theme:
    name: mkdocs
    nav_style: dark
    highlightjs: true
    hljs_languages:
        - Bash
        - HTML
        - Java
        - JavaScript
        - Perl
        - Python
        - R
        - rust
        - yaml
