site_name: software notes
nav:
    - "": README.md
    - Genetic analysis:
      - AA.md
      - CRISPR.md
      - misc.md
      - NGS.md
      - pharmacogenomics.md
      - prottrans.md
      - single-cell.md
    - Statistcal learning: SL.md
    - Artificial intelligence: AI.md
theme:
    name: mkdocs
    nav_style: dark
    highlightjs: true
    hljs_languages:
        - Bash
        - HTML
        - Java
        - JavaScript
        - Perl
        - Python
        - R
        - rust
        - yaml
